function XML_string = CreateLiIon4(Fit)
XML_string = CreatePreamble();
XML_string = [XML_string, CreateLookup(Fit)];
XML_string = [XML_string, CreateConnection()];
XML_string = [XML_string, CreateEnd()];
% XML_string = [ CreatePreamble(), CreateLookup(Fit), CreateConnection(), CreateEnd()];
end


function LookupCache = CreateLookup(Fit)
LookupCache = '';
for i =  1:length(Fit.P_namen)
    LookupCache  = [LookupCache, '\n', CreateXMLNode( Fit.P_namen{i}, squeeze( Fit.T_lookup), squeeze( Fit.SOC_lookup), squeeze( Fit.P_lookup(:, :,i))) ];
end
end

function xml = CreatePreamble()
xml = [...
    '<?xml version="1.0" encoding="UTF-8"?>\n' ...
    '<Configuration>\n' ...
    '<Options>\n' ...
    '</Options>\n' ...
    '<Observer>\n' ...
    ' <Electrical>\n' ...
    ' </Electrical>\n' ...
    ' <Thermal>\n' ...
    ' </Thermal>\n' ...
    '</Observer>\n' ...
    '<ThermalMaterials>\n' ...
    '</ThermalMaterials>\n' ...
    '<Coolings>\n' ...
    '</Coolings>\n' ...
    '<CustomDefinitions>\n'];
end

function xml = CreateEnd()
xml = [...
    '</CustomDefinitions>\n' ...
    '<RootElement ref="LiBat4"/>\n' ...
    '</Configuration>\n'];

end

function xml = CreateConnection()
xml = [ ...
    '<LiBat4 class="CellElement" observable="True">\n' ... 
    ' <ThermalState class="ThermalState" cache="True">\n' ...
    '  <InitialThermalState>23</InitialThermalState>\n' ...
    ' </ThermalState>\n' ...
    ' <Soc class="Soc" cache="True">\n' ...
    '   <MaxCapacity>2.05</MaxCapacity>\n' ...
    '   <InitialSoc>55</InitialSoc>\n' ...
    '   <MeasurementPoints>5, 10, 20, 23, 35, 50, 65, 80, 90</MeasurementPoints>\n' ...
    ' </Soc>\n' ...
    ' <Children>\n' ...
    '  <OhmicResistance ref="Rser"/>\n' ...
    '  <VoltageSource ref="OCV"/>\n' ...
    '  <ZarcElements ref="Zarc1"/>\n' ...
    '  <ZarcElements ref="Zarc2"/>\n' ...
    ' </Children>\n' ...
    '</LiBat4>\n'];
end