function XML_string = CreateLiIon4(Fit,cap)
XML_string = CreatePreamble();
XML_string = [XML_string, CreateLookup(Fit)];
XML_string = [XML_string, CreateConnection(cap)];
XML_string = [XML_string, CreateEnd()];
% XML_string = [ CreatePreamble(), CreateLookup(Fit), CreateConnection(), CreateEnd()];
end


function LookupCache = CreateLookup(Fit)
LookupCache = '';
for i =  1:length(Fit.P_namen)
    LookupCache  = [LookupCache, '\n', CreateXMLNode( Fit.P_namen{i}, squeeze( Fit.T_lookup), squeeze( Fit.SOC_lookup), squeeze( Fit.P_lookup(:, :,i))) ];
end
end

function xml = CreatePreamble()
xml = [...
    '<?xml version="1.0" encoding="UTF-8"?>\n' ...
    '<Configuration>\n' ...
    '<Options>\n' ...
    '</Options>\n' ...
    '<Observer>\n' ...
    ' <Electrical>\n' ...
    ' </Electrical>\n' ...
    ' <Thermal>\n' ...
    ' </Thermal>\n' ...
    '</Observer>\n' ...
    '<ThermalMaterials>\n' ...
    '</ThermalMaterials>\n' ...
    '<Coolings>\n' ...
    '</Coolings>\n' ...
    '<CustomDefinitions>\n'];
end

function xml = CreateEnd()
xml = [...
    '</CustomDefinitions>\n' ...
    '<RootElement ref="LiBat4"/>\n' ...
    '</Configuration>\n'];

end

function xml = CreateConnection(cap)
xml = [ ...
    '<LiBat4 class="CellElement" observable="True">\n' ... 
    ' <ThermalState class="ThermalState" cache="True">\n' ...
    '  <InitialThermalState>23</InitialThermalState>\n' ...
    ' </ThermalState>\n' ...
    ' <Soc class="Soc" cache="True">\n' ...
    '   <MaxCapacity> '... 
     , cap, ...
     '</MaxCapacity>\n' ...
    '   <InitialSoc>55</InitialSoc>\n' ...
    '   <MeasurementPoints>5, 10, 20, 23, 35, 50, 65, 80, 90</MeasurementPoints>\n' ...
    ' </Soc>\n' ...
    ' <Children>\n' ...
    '  <OhmicResistance ref="Rser"/>\n' ...
    '  <VoltageSource class="OCV">\n' ...
    '   <Object ref="OCV"/>\n' ...
    '  </VoltageSource>\n' ...
    '  <NegativeElectrode class="Rmphn">\n' ...
    '   <LookupOhmicResistance ref="R_ct_A_lookup"/>\n' ...
    '   <LookupTau ref="Tau_dl_A_lookup"/>\n' ...
    '   <OhmicResistance_RMP ref="RMP_lookup"/>\n' ...
    '  </NegativeElectrode>\n' ...
    '  <PositiveElectrode class="SerialTwoPort">\n' ...
    '   <Children>\n' ...
    '    <Rmphn class="Rmphn">\n' ...
    '     <LookupOhmicResistance ref="R_ct_B_lookup"/>\n' ...
    '     <LookupTau ref="Tau_dl_B_lookup"/>\n' ...
    '     <OhmicResistance_RMP ref="R_D_B_lookup"/>\n' ...
    '    </Rmphn>\n' ...
    '    <Diffusion class="SphericalDiffusion">\n' ...
    '     <OhmicResistance ref="R_D_B_lookup"/>\n' ...
    '     <Tau ref="Tau_D_B_lookup"/>\n' ...
    '    </Diffusion>\n' ...
    '   </Children>\n' ...
    '  </PositiveElectrode>\n' ...
    '  <Electrolyte class="ParallelRC">\n' ...
    '  <LookupOhmicResistance ref="R_DP_lookup"/>\n' ...
    '  <LookupTau ref="Tau_DP_lookup"/>\n' ...
    '  </Electrolyte>\n' ...
    ' </Children>\n' ...
     '</LiBat4>\n'];
end