function returnValue = CreateXMLNode( name, T_vec, Soc_vec, values)
returnValue = '';
T = MakeReadableNumber(T_vec');
S = MakeReadableNumber(Soc_vec);
val = MakeReadableNumber(values);

% Creates complete element
if strcmp(name, 'Rser')
    returnValue = [
    '<Rser class="OhmicResistance">\n' ...
    ' <Object class="LookupObj2dWithState">\n' ...
    CreateLookup(val, T, S), ...
    ' </Object>' ...
    '</Rser>'];
% Creates only lookups
elseif strcmp(name, 'R_ct_A')
    returnValue = [
     ' <R_ct_A_lookup class="LookupObj2dWithState">\n' ...
    CreateLookup(val, T, S), ...
    ' </R_ct_A_lookup >'];
elseif strcmp(name, 'Tau_dl_A')
    returnValue = [
     ' <Tau_dl_A_lookup class="LookupObj2dWithState">\n' ...
    CreateLookup(val, T, S), ...
    ' </Tau_dl_A_lookup>\n'];
elseif strcmp(name, 'RMP')
        returnValue = [
     ' <RMP_lookup class="LookupObj2dWithState">\n' ...
    CreateLookup(val, T, S), ...
    ' </RMP_lookup>\n'];
elseif strcmp(name, 'R_ct_B')
     returnValue = [
     ' <R_ct_B_lookup class="LookupObj2dWithState">\n' ...
    CreateLookup(val, T, S), ...
    ' </R_ct_B_lookup >\n'];
elseif strcmp(name, 'Tau_dl_B')
       returnValue = [
     ' <Tau_dl_B_lookup class="LookupObj2dWithState">\n' ...
    CreateLookup(val, T, S), ...
    ' </Tau_dl_B_lookup>\n']; 
elseif strcmp(name, 'R_D_B')
     returnValue = [
     ' <R_D_B_lookup class="LookupObj2dWithState">\n' ...
    CreateLookup(val, T, S), ...
    ' </R_D_B_lookup>\n'];
elseif strcmp(name, 'Tau_D_B')
    returnValue = [
     ' <Tau_D_B_lookup class="LookupObj2dWithState">\n' ...
    CreateLookup(val, T, S), ...
    ' </Tau_D_B_lookup>\n'];
elseif strcmp(name, 'R_DP')
    returnValue = [
     ' <R_DP_lookup class="LookupObj2dWithState">\n' ...
    CreateLookup(val, T, S), ...
    ' </R_DP_lookup>\n'];
elseif strcmp(name, 'Tau_DP')
    returnValue = [
     ' <Tau_DP_lookup class="LookupObj2dWithState">\n' ...
    CreateLookup(val, T, S), ...
    ' </Tau_DP_lookup>\n'];
elseif strcmp(name, 'R_slow')
     returnValue = [
     ' <R_slow_lookup class="LookupObj2dWithState">\n' ...
    CreateLookup(val, T, S), ...
    ' </R_slow_lookup>\n'];
elseif strcmp(name, 'Tau_slow')
    returnValue = [
     ' <Tau_slow_lookup class="LookupObj2dWithState">\n' ...
    CreateLookup(val, T, S), ...
    ' </Tau_slow_lookup>\n'];
else
%     error( [ 'Dont know how to extract parameter ', name])
end

function lookup = CreateLookup(val, T, S)
lookup = [ ...
    '  <RowState cacheref="ThermalState"/>\n' ...
    '  <ColState cacheref="Soc"/>\n' ...
    '  <LookupData>\n' ...
    , val, ...
    '</LookupData>\n ' ...
    '<MeasurementPointsRow>\n' ...
    ,T, ...
    '</MeasurementPointsRow>\n' ...
    '<MeasurementPointsColumn>\n' ...
    , S, ...
    '</MeasurementPointsColumn>\n'];

function val = MakeReadableNumber(values)
    val = mat2str(values);
    val = strrep( val(2:end-1), ' ' , ','); % erase []
    val = strrep( val(2:end-1), ';' , ';\n'); % erase []
