



Modellliste.Implementierung.RMP_HN1RC_MFRC.Funktionsname = 'RMP_HN1RC';
Modellliste.Implementierung.RMP_HN1RC_MFRC.inputs = {'R_ct','Tau_dl','Phi_HN','R_MP'};
Modellliste.Implementierung.RMP_HN1RC_MFRC.Zfun = [ ...
    '(R_MP.*(R_ct./(1+1i.*w.*Tau_dl).^Phi_HN)).^0.5'...
    '.*coth((R_MP./(R_ct./(1+1i.*w.*Tau_dl).^Phi_HN)).^0.5)'...
    ];
Modellliste.Implementierung.RMP_HN1RC_MFRC.Zfun_HF = [...
    '(R_MP.*(R_ct./(1+1i.*w.*Tau_dl).^Phi_HN)).^0.5'...
    '.*coth((R_MP./(R_ct./(1+1i.*w.*Tau_dl).^Phi_HN)).^0.5)'...
    '-R_ct./(1+1i.*w.*Tau_dl).^Phi_HN'...
    ];
Modellliste.Implementierung.RMP_HN1RC_MFRC.Zfun_MF = 'R_ct./(1+1i.*w.*Tau_dl).^Phi_HN';
Modellliste.Implementierung.RMP_HN1RC_MFRC.Zfun_LF = ['0'];
