



Modellliste.Implementierung.RMP_2HN1RC.Funktionsname = 'RMP_2HN1RC';
Modellliste.Implementierung.RMP_2HN1RC.inputs = {'R_ct1','Tau_dl1','R_ct2','Tau_dl2','Phi_HN2','R_MP'};
Modellliste.Implementierung.RMP_2HN1RC.Zfun = [ ...
    '(R_MP.*(R_ct1./(1+1i.*w.*Tau_dl1)+R_ct2./(1+1i.*w.*Tau_dl2).^Phi_HN2)).^0.5'...
    '.*coth((R_MP./(R_ct1./(1+1i.*w.*Tau_dl1)+R_ct2./(1+1i.*w.*Tau_dl2).^Phi_HN2)).^0.5)'...
    ];
Modellliste.Implementierung.RMP_2HN1RC.Zfun_HF = ['0'];
Modellliste.Implementierung.RMP_2HN1RC.Zfun_MF = [...
    '(R_MP.*(R_ct1./(1+1i.*w.*Tau_dl1)+R_ct2./(1+1i.*w.*Tau_dl2).^Phi_HN2)).^0.5'...
    '.*coth((R_MP./(R_ct1./(1+1i.*w.*Tau_dl1)+R_ct2./(1+1i.*w.*Tau_dl2).^Phi_HN2)).^0.5)'];
Modellliste.Implementierung.RMP_2HN1RC.Zfun_LF = ['0'];
